# PlatformIO pre: script — gzip-embed data/ web assets into a C++ header.
Import("env")  # type: ignore  # noqa: F821 — PlatformIO injects Import

from pathlib import Path
import gzip

pio_env = env  # type: ignore  # noqa: F821


def _c_array(symbol_name: str, payload: bytes) -> str:
    lines = [f"static const uint8_t {symbol_name}[] PROGMEM = {{"]
    for offset in range(0, len(payload), 16):
        chunk = payload[offset : offset + 16]
        hex_bytes = ", ".join(f"0x{byte:02x}" for byte in chunk)
        trailing = "," if offset + 16 < len(payload) else ""
        lines.append(f"    {hex_bytes}{trailing}")
    lines.append("};")
    return "\n".join(lines)


def generate_embedded_web_assets():
    project_dir = Path(pio_env["PROJECT_DIR"])
    assets = [
        {
            "source": project_dir / "data" / "index.html",
            "symbol": "kEmbeddedIndexHtmlGz",
            "length_symbol": "kEmbeddedIndexHtmlGzLen",
            "mime": "text/html",
        },
        {
            "source": project_dir / "data" / "css" / "all.css",
            "symbol": "kEmbeddedAllCssGz",
            "length_symbol": "kEmbeddedAllCssGzLen",
            "mime": "text/css",
        },
    ]

    output_dir = project_dir / "include" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "EmbeddedWebAssets.h"

    parts = [
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "#include <pgmspace.h>",
        "",
        "// Generated by scripts/embed_web_assets.py — do not edit.",
        "",
    ]

    for asset in assets:
        source_path = asset["source"]
        if not source_path.is_file():
            raise FileNotFoundError(f"Missing web asset for embed: {source_path}")
        raw_bytes = source_path.read_bytes()
        gzip_bytes = gzip.compress(raw_bytes, compresslevel=9)
        parts.append(_c_array(asset["symbol"], gzip_bytes))
        parts.append(
            f"static const size_t {asset['length_symbol']} = {len(gzip_bytes)};"
        )
        parts.append(
            f'static const char {asset["symbol"]}Mime[] = "{asset["mime"]}";'
        )
        parts.append("")
        print(
            f"embed_web_assets: {source_path.relative_to(project_dir)} "
            f"{len(raw_bytes)} -> {len(gzip_bytes)} gzip bytes"
        )

    parts.append("static const bool kEmbeddedWebAssetsGzip = true;")
    parts.append("")

    output_path.write_text("\n".join(parts), encoding="utf-8")
    print(f"embed_web_assets: wrote {output_path.relative_to(project_dir)}")


generate_embedded_web_assets()
