#pragma once

#define LOG_LEVEL_DETAIL_DEBUG 0
#define LOG_LEVEL_DEBUG 1
#define LOG_LEVEL_INFO 2
#define LOG_LEVEL_WARNING 3
#define LOG_LEVEL_ERROR 4
#define LOG_LEVEL_NOTHING 5

#define LOG_LEVEL LOG_LEVEL_DEBUG
#define CON_DEBUG

#define WIFI_DEFAULT_BSSID "z2m-gateway"
#define WIFI_DEFAULT_PASSWORD "00000000"
#define WIFI_DEFAULT_DEVICE_NAME "z2m-gateway"
#define WIFI_DEFAULT_AP_IP "192.168.0.1"

#define DEFAULT_MQTT_SERVER "192.168.1.1"
#define DEFAULT_MQTT_PORT 1883
#define DEFAULT_MQTT_RECONNECT_MS 3000
#define DEFAULT_MQTT_CLIENT_TIMEOUT_MS 200
#define DEFAULT_MQTT_BASE_TOPIC "z2m"
#define DEFAULT_MQTT_CLIENT_ID "z2m-mqtt"

#define MQTT_CLIENT_TIMEOUT_MS_MIN 50
#define MQTT_CLIENT_TIMEOUT_MS_MAX 1500

#define DEFAULT_ZIGBEE_CHANNEL 15
#define DEFAULT_PERMIT_JOIN_SEC 180

#define FIRMWARE_VERSION "0.1.0"

#define DEVICE_MAP_SLOTS 12
